apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "5"
    deployment.kubernetes.io/max-replicas: "7"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-05-23T15:38:36Z"
  generation: 2
  labels:
    app: webapp
    pod-template-hash: 6684ccd7b8
  name: webapp-6684ccd7b8
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: webapp
    uid: 646e50ad-9453-4575-ac5a-dea72ee29706
  resourceVersion: "15731"
  uid: 1648446c-a783-4694-9643-889c4e6de4ff
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
      pod-template-hash: 6684ccd7b8
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
        pod-template-hash: 6684ccd7b8
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  fullyLabeledReplicas: 5
  observedGeneration: 2
  readyReplicas: 5
  replicas: 5
