apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  labels:
    name: nginx-resolver
spec:
  containers:
  - name: nginx-resolver
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name:  nginx-resolver-service
spec:
  selector:
    name: nginx-resolver
  type:  ClusterIP
  ports:
  - name:  6379-6379
    port:  6379
    targetPort:  6379

---

apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep", "1000"]